/**
 * @author Maria Fernanda Serna
 */

export const VIDEOS_LIST_REQUEST = 'VIDEOS_LIST_REQUEST';
export const VIDEOS_LIST_REQUEST_FAIL = 'VIDEOS_LIST_REQUEST_FAIL';
export const VIDEOS_LIST_REQUEST_SUCCESS = 'VIDEOS_LIST_REQUEST_SUCCESS';
export const SET_ERROR = 'SET_ERROR';
export const VIDEOS_VOTE_REQUEST = 'VIDEOS_VOTE_REQUEST';
export const VIDEOS_VOTE_REQUEST_FAIL = 'VIDEOS_VOTE_REQUEST_FAIL';
export const VIDEOS_VOTE_REQUEST_SUCCESS = 'VIDEOS_VOTE_REQUEST_SUCCESS';
export const VIDEOS_UPLOAD_REQUEST = 'VIDEOS_UPLOAD_REQUEST';
export const VIDEOS_UPLOAD_REQUEST_FAIL = 'VIDEOS_UPLOAD_REQUEST_FAIL';
export const VIDEOS_UPLOAD_REQUEST_SUCCESS = 'VIDEOS_UPLOAD_REQUEST_SUCCESS';
