source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BuzzCuts' do
	pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'
end
