/**
 * @author Maria Fernanda Serna
 */

export const THEME_LIST_REQUEST = 'THEME_LIST_REQUEST';
export const THEME_LIST_REQUEST_FAIL = 'THEME_LIST_REQUEST_FAIL';
export const THEME_LIST_REQUEST_SUCCESS = 'THEME_LIST_REQUEST_SUCCESS';
export const SET_ERROR = 'SET_ERROR';

export const THEME_LIST_TODAY_REQUEST = 'THEME_LIST_TODAY_REQUEST';
export const THEME_LIST_TODAY_REQUEST_FAIL = 'THEME_LIST_TODAY_REQUEST_FAIL';
export const THEME_LIST_TODAY_REQUEST_SUCCESS = 'THEME_LIST_TODAY_REQUEST_SUCCESS';

export const THEME_LIST_YESTERDAY_REQUEST = 'THEME_LIST_YESTERDAY_REQUEST';
export const THEME_LIST_YESTERDAY_REQUEST_FAIL = 'THEME_LIST_YESTERDAY_REQUEST_FAIL';
export const THEME_LIST_YESTERDAY_REQUEST_SUCCESS = 'THEME_LIST_YESTERDAY_REQUEST_SUCCESS';
