/**
 * @author Maria Fernanda Serna
 */

export const THEME_SCORES_REQUEST = 'THEME_SCORES_REQUEST';
export const THEME_SCORES_REQUEST_FAIL = 'THEME_SCORES_REQUEST_FAIL';
export const THEME_SCORES_REQUEST_SUCCESS = 'THEME_SCORES_REQUEST_SUCCESS';

export const THEME_RANKINGS_REQUEST = 'THEME_RANKINGS_REQUEST';
export const THEME_RANKINGS_REQUEST_FAIL = 'THEME_RANKINGS_REQUEST_FAIL';
export const THEME_RANKINGS_REQUEST_SUCCESS = 'THEME_RANKINGS_REQUEST_SUCCESS';
