/**
 * @author Maria Fernanda Serna
 */

export const SETTINGS_UPDATE_REQUEST = 'SETTINGS_UPDATE_REQUEST';
export const SETTINGS_UPDATE_REQUEST_FAIL = 'SETTINGS_UPDATE_REQUEST_FAIL';
export const SETTINGS_UPDATE_REQUEST_SUCCESS = 'SETTINGS_UPDATE_REQUEST_SUCCESS';
export const SET_ERROR = 'SET_ERROR';
export const SETTINGS_GET_REQUEST = 'SETTINGS_GET_REQUEST';
export const SETTINGS_GET_REQUEST_FAIL = 'SETTINGS_GET_REQUEST_FAIL';
export const SETTINGS_GET_REQUEST_SUCCESS = 'SETTINGS_GET_REQUEST_SUCCESS';
